### ISSUE TITLE
About page refresh: v9 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/about#18]
Anticipating the arrival of v9 and other additions ([pathway search](http://beta.pathwaycommons.org/pathways/#/search), [guide](http://pathwaycommons.github.io/guide/)), I am seeking input on a refresh of the About homepage.

Development version would be located on [gh-pages](http://pathwaycommons.github.io/about/) branch.

![home](https://cloud.githubusercontent.com/assets/4706307/25401795/b5d9cdb2-29c4-11e7-8d7c-f90397ccc8b9.png)

**Comment by gbader** [comment]
great mock-up, thanks.  Here are some comments
-splash - could we lay the graphics out horizontally to better use the space?
-need a better distinction between bio and compbio focused - e.g. biopax validator is mostly a web service, so it is web, not desktop - same with web services. CyPath2 is geared for cytoscape users (mostly biologists). Also, the guide should be emphasized more - move "above the fold"
-let's move legacy to an FAQ answer
-'links' is a bit uninformative - better to embed that content into FAQ or other sections, except for 'contact' which is important, so ok at the bottom of the page as proposed

**Comment by jvwong** [comment]
Updates
  - Horizontal splash  
  - Blurb for Guide
  - Sections
    - Apps
    - Data
      - *Linked data* sub-section
    - Tools
      - *Data visualization and analysis*, *Developer resources* and *Experimental* sub-sections 
  - Moved 'links' content to other sections
  - Added citations where available

![pathwaycommons_v9](https://cloud.githubusercontent.com/assets/4706307/25663038/9e6a3a42-2fe4-11e7-99df-2a4b0300bad8.png)

**Comment by gbader** [comment]
better! 
-news is less important than training and apps. Could it be hidden behind a notification icon e.g. on linkedin?
-the training and apps section should be visible 'above the fold'. At least for apps, users will want to search much more often than read a large graphic about what PC is. many people are using pcviz and I hope pathway search will be very popular.
-linked data - could we put into an FAQ - not sure how many users.
-'experimental' doesn't sound very confident. I wonder if dev tools should be on a separate page
-chibe - de-emphasize - it hasn't worked when we've used it. Not sure if anyone is using it - could check with ozgun. Could sort roughly by number of users. cypath2 has 16000 downloads, paxtoolsr has thousands of downloads per year

**Comment by gbader** [comment]
also, not sure if we need that much real estate for training

**Comment by jvwong** [comment]
![pathwaycommons_v9](https://cloud.githubusercontent.com/assets/4706307/25862683/f2dc5dfe-34b6-11e7-871f-87b7f1e96fd7.png)

**Comment by IgorRodchenkov** [comment]
Great.
There is no Transfac anymore - MSigDB (C3 TFT motif  gene sets) is.

**Comment by jvwong** [comment]
Prototype up on [github pages](http://pathwaycommons.github.io/about/).

**Comment by jvwong** [comment]
Wanted! What's new/different in version 9 modal  - (@IgorRodchenkov)

**Comment by gbader** [comment]
Prototype looks great.
-could we add a search button to PCVIz as well (it's on the pathway search bar)
-Should we add an example search to the pathway search input field, similar to PCViz?
-Could we make the guide more prominent - this is really important content - maybe "Pathway analysis online textbook" as prominent as the apps?
-Data section: The "Show details" button could be integrated into the file downloads bar as a standard expand/collapse UI element to save vertical space - similar for web services
-"for archival" -> "for archiving"
-The font is too small and thin in certain areas e.g. the Tools description text. I have more trouble reading it than typical for websites I regularly use. Maybe make the smallest font the same size as the smallest font at https://www.google.ca/intl/en/about/
-Let's remove the 'desktop' tag - at least it doesn't make sense for paxtoolsR and should be on cypath2. If this is just a mistake, then let's make an R tag for paxtoolsr

**Comment by jvwong** [comment]
Updated in 7b3603f32f037c10db4479432dfa824bcdee65e2.

- Moved splash image to a 'v9' modal.

**Comment by IgorRodchenkov** [comment]
Do we really need that "Statistics" (it's about the PC2 web services only; perhaps, worth changing title...) section and chart on the home page? Looks not very useful to me. I think, PC2/datasources page is enough, no? Why to duplicate and maintain the counts...

**Comment by jvwong** [comment]
Dropped the statistics and put back the 'infographic' image in a9d83639f3437e31b8b91c88a5e13b0ac64beaf9.

**Comment by jvwong** [comment]
In attempts to be more transparent about PC & data, propose to update:

1. Subtitle: 
 > Access and discover data integrated from public pathway and interaction databases

2. Splash:

  ![figure_overview](https://user-images.githubusercontent.com/4706307/27555606-53fb3f3a-5a80-11e7-99e8-1a11afaa027b.png)

3. FAQ: How is the pathway data integrated?

> Pathway data are downloaded directly from source databases. Each source has been created differently, some by manual extraction of pathway information from the literature and some by computational prediction. Warehouse data (canonical molecules, ontologies) are converted to BioPAX utility classes and saved as the initial BioPAX model, which forms the foundation for integrating  data and for id-mapping. Pathway and binary interaction data (interactions, participants) are normalized next and merged into the database. Original reference molecules are replaced with the corresponding BioPAX warehouse objects.
