### ISSUE TITLE
'PC API' app: to update link to and move locally.

### ISSUE THREAD

**Issue by IgorRodchenkov** [PathwayCommons/about#21]
The PC api app (currently hosted at http://sanderlab.org/pcapi and linked from the new PC homepage) need to be reviewed and probably updated before or shortly after PC9 release.

**Comment by jvwong** [comment]
Regarding today's meeting with Gary: Plan to remove these 'Idea Lab' items from the homepage and place as simple list items (e.g. 'Other developer resources') on the about [README](https://github.com/PathwayCommons/about/blob/master/README.md). 

Should still be reviewed and updated.
