### ISSUE TITLE
Migrate PWC search to HTTPS?

### ISSUE THREAD

**Issue by sacdallago** [PathwayCommons/about#33]
Since Chrome has started telling users that http traffic is "not secure", for user confidence, it might be worth considering redirecting http traffic to https.

This is especially true for users coming from UniProt, which links to http (not https).

![image](https://user-images.githubusercontent.com/6240943/94864755-c388bf80-043c-11eb-9dfe-424e30583a0b.png)

**Comment by gbader** [comment]
Looks like we need a redirect from http->https

**Comment by jvwong** [comment]
That should be working - isn't it for you?
